send_sms:
  name: service_name
  description: service_description
  fields:
    target:
      name: target_name
      description: target_description
      required: true
      example: notify.mon_telephone
      selector:
        text:
    message:
      name: message_name
      description: message_description
      required: true
      example: Piscine hors gel !
      selector:
        text:
